### ISSUE TITLE
installer.sh does not check for pip3 before installing.

### ISSUE THREAD

**Issue by wanderling** [techcoder20/RPI-PowerlineShell-Installer#2]
On Retropie image, with lxde installed as an addon to Retropie, pip3 is not installed by default. This installer does not explicitly check for or try to install pip3 prior to calling it. If pip3 doesn't exist the installer fails.

`pi@retropie:~/build/RPI-PowerlineShell-Installer $ ./install.sh`
`Reading package lists... Done`
`Building dependency tree`
`Reading state information... Done`
`fonts-fantasque-sans is already the newest version (1.7.2~alpha.3~dfsg-1).`
`fonts-powerline is already the newest version (2.7-2).`
`python3 is already the newest version (3.7.3-1).`
`python-pip is already the newest version (18.1-5+rpt1).`
`0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.`
`sudo: pip3: command not found`
`Failed to install powerline shell with pip3`

**Comment by techcoder20** [comment]
@wanderling I have fixed it please do a git pull and try again

**Comment by wanderling** [comment]
That works! Thanks!

**Comment by techcoder20** [comment]
> That works! Thanks!

Np 😀
